name: test_a
on:
  push:
#   push:
#       branches: [ main ]
#   pull_request:
#       branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mpi4py/setup-mpi@v1
      - name: install packages
        run: |
          sudo apt update 
          sudo apt install libpcl-dev libomp-dev libvtk9-dev openmpi-bin libopenmpi-dev
          sudo apt upgrade -y
          sudo apt install python3-pip
          pip install pybind11
      # - name: install pybind
      #   run: |
      #     git clone https://github.com/pybind/pybind11.git pybind
      #     cmake -S /tmp/pybind -B /tmp/pybind/build -DCMAKE_BUILD_TYPE=Release
      #     cd /tmp/pybind/build && make
      #     cd /tmp/pybind/build && sudo make install
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
